backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/images'
public_folder: '/_astro'

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/content/post'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - { label: 'Image', name: 'image', widget: 'string' }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
      - { label: 'Update Date', name: 'updateDate', widget: 'datetime', required: false }
      - { label: 'Draft', name: 'draft', widget: 'boolean', required: false }
      - { label: 'Reading Time', name: 'readingTime', widget: 'number', required: false }
      - { label: 'Start Date', name: 'startDate', widget: 'datetime', required: false }
      - { label: 'End Date', name: 'endDate', widget: 'datetime', required: false }
      - { label: 'Location', name: 'location', widget: 'string', required: false }
      - { label: 'Organizer', name: 'organizer', widget: 'string', required: false }

  - name: 'faculty'
    label: 'Faculty'
    folder: 'src/content/faculty'
    create: true
    extension: 'json'
    format: 'json'
    fields:
      - { label: 'Name', name: 'name', widget: 'string', required: false }
      - { label: 'Position', name: 'position', widget: 'string', required: false }
      - { label: 'Department', name: 'department', widget: 'string', required: false }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Biography', name: 'biography', widget: 'text', required: false }
      - label: 'Socials'
        name: 'socials'
        widget: 'list'
        required: false
        fields:
          - { label: 'Platform', name: 'platform', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
      - label: 'Classes'
        name: 'classes'
        widget: 'object'
        required: false
        fields:
          - { label: 'Class Name', name: 'className', widget: 'string' }
          - { label: 'Class ID', name: 'classID', widget: 'string' }

  - name: 'marquee'
    label: 'Marquee Announcements'
    folder: 'src/content/marquee'
    create: true
    extension: 'json'
    format: 'json'
    fields:
      - { label: 'ID', name: 'id', widget: 'string', required: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Message', name: 'message', widget: 'text' }
      - { label: 'Start Date', name: 'startDate', widget: 'datetime', required: false }
      - { label: 'End Date', name: 'endDate', widget: 'datetime', required: false }
      - { label: 'Link', name: 'link', widget: 'string', required: false }

  - name: 'events'
    label: 'Events'
    folder: 'src/content/events'
    create: true
    extension: 'json'
    format: 'json'
    fields:
      - { label: 'ID', name: 'id', widget: 'string', required: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Start Date', name: 'startDate', widget: 'datetime' }
      - { label: 'End Date', name: 'endDate', widget: 'datetime' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Organizer', name: 'organizer', widget: 'string', required: false }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Link', name: 'link', widget: 'string', required: false }
